apiVersion: v1
kind: Service
metadata:
  name: {{ include "rottenpotatoes.fullname" . }}
  labels:
    {{- include "rottenpotatoes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rottenpotatoes.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.mongodb.db.port }}
      targetPort: {{ .Values.mongodb.db.port }}
  type: ClusterIP
